AWSTemplateFormatVersion: 2010-09-09
Description: |
  'Kittens Carousel is a static 
  website application deployed with
  Apache Web Server on AWS Elastic 
  Compute Cloud (EC2) Instance using
  AWS Cloudformation Service.'
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP for Apache web server and SSH for scure connection" # Required
      GroupName: moztSecGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
  MozWebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08a52ddb321b32a8c
      InstanceType: t2.micro
      KeyName: mozt
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          yum update -y
          yum install httpd -y
          FOLDER="https://raw.githubusercontent.com/miracozturk/aws-projects/main/Project-101-kittens-carousel-static-website-ec2%26CF/static-web/"
          cd /var/www/html
          wget $FOLDER/index.html
          wget $FOLDER/cat0.jpg
          wget $FOLDER/cat1.jpg
          wget $FOLDER/cat2.jpg
          wget $FOLDER/cat3.png
          systemctl start httpd
          systemctl enable httpd
Outputs:
  WebSiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MozWebServerHost.PublicDnsName
